-- Baseline the schema previously managed by Hibernate ddl-auto=update.
-- CREATE IF NOT EXISTS keeps adoption safe for existing staging and production schemas.

CREATE TABLE IF NOT EXISTS app_users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(320) NOT NULL,
    password_hash varchar(255) NOT NULL,
    organization_id varchar(100) NOT NULL,
    enabled boolean NOT NULL,
    CONSTRAINT uk_app_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS app_user_roles (
    app_user_id bigint NOT NULL,
    roles varchar(255),
    CONSTRAINT fk_app_user_roles_user FOREIGN KEY (app_user_id) REFERENCES app_users (id)
);

CREATE TABLE IF NOT EXISTS candidates (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id varchar(100) DEFAULT 'default' NOT NULL,
    name varchar(255), email varchar(255), location varchar(255), current_title varchar(255),
    years_experience integer, cv_text oid, created_at timestamp(6) with time zone
);

CREATE TABLE IF NOT EXISTS jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id varchar(100) DEFAULT 'default' NOT NULL,
    title varchar(255), level varchar(255), summary varchar(500), location varchar(255),
    employment_type varchar(255), salary_range varchar(255), department varchar(255), tone varchar(255),
    responsibilities oid, required_qualifications oid, preferred_qualifications oid,
    soft_skills oid, benefits oid, created_at timestamp(6) with time zone
);

CREATE TABLE IF NOT EXISTS cv_documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id varchar(100) DEFAULT 'default' NOT NULL,
    candidate_id bigint,
    original_filename varchar(255) NOT NULL,
    content_type varchar(255) NOT NULL,
    file_size bigint NOT NULL,
    sha256 varchar(64) NOT NULL,
    source varchar(32) NOT NULL,
    status varchar(32) NOT NULL,
    extracted_text oid,
    text_length integer NOT NULL,
    ingestion_error oid,
    imported_at timestamp(6) with time zone,
    CONSTRAINT fk_cv_documents_candidate FOREIGN KEY (candidate_id) REFERENCES candidates (id),
    CONSTRAINT uk_cv_documents_organization_sha256 UNIQUE (organization_id, sha256)
);

CREATE TABLE IF NOT EXISTS candidate_evaluations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id varchar(100) DEFAULT 'default' NOT NULL,
    candidate_id bigint NOT NULL,
    job_id bigint NOT NULL,
    skills_match_score integer NOT NULL,
    experience_relevance_score integer NOT NULL,
    education_fit_score integer NOT NULL,
    achievement_impact_score integer NOT NULL,
    keyword_density_score integer NOT NULL,
    employment_gap_score integer NOT NULL,
    readability_score integer NOT NULL,
    ai_confidence_score integer NOT NULL,
    overall_fit_score integer NOT NULL,
    ai_explanation oid,
    created_at timestamp(6) with time zone,
    CONSTRAINT fk_candidate_evaluations_candidate FOREIGN KEY (candidate_id) REFERENCES candidates (id),
    CONSTRAINT fk_candidate_evaluations_job FOREIGN KEY (job_id) REFERENCES jobs (id)
);

CREATE TABLE IF NOT EXISTS security_audit_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id varchar(100), actor_user_id bigint, actor_email varchar(320),
    target_user_id bigint, target_email varchar(320), target_identifier_hash varchar(64),
    client_ip_hash varchar(64), event_type varchar(40) NOT NULL, outcome varchar(20) NOT NULL,
    details varchar(500), created_at timestamp(6) with time zone NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_security_audit_org_created
    ON security_audit_events (organization_id, created_at);
CREATE INDEX IF NOT EXISTS idx_security_audit_created ON security_audit_events (created_at);

-- Hibernate-generated enum checks become stale whenever Java adds an enum value.
-- Java converters remain the validation boundary for these columns.
ALTER TABLE security_audit_events
    DROP CONSTRAINT IF EXISTS security_audit_events_event_type_check;
ALTER TABLE security_audit_events
    DROP CONSTRAINT IF EXISTS security_audit_events_outcome_check;
